### ISSUE TITLE
Query: lm_reverse_list in model/dataset.py has 66 face landmark points specified

### ISSUE THREAD

**Issue by GayatriPurandharT** [yaojieliu/ECCV20-STDN#10]
Hi, I have processed the data of SiW-M dataset.
The input folder contains live and spoof images- with cropped faces and 164 landmarks npy file.
I followed the same folder structure as provided in this repo.
**problem**:
`IndexError: index 16 is out of bounds for axis 0 with size 1`
Did you sample 66 points out of 148 or did you use some library which produces 66 points?
I used the face-alignment (https://github.com/1adrianb/face-alignment) that you suggested in a previous issue.
Please help me to choose the right landmark list to be able to train the model.
Thank you very much!

**Comment by GayatriPurandharT** [comment]
The error was due to the mismatch in dimension of my input npy face landmarks and the one expected in dataset.py. I had a 3d nympy array of landmarks. I converted back to 2d and that solved this issue.

**Comment by saiamrit** [comment]
Hi @GayatriPurandharT. I am also currently trying to replicate the results of this paper but I am unable to find the SiW-M dataset. Can you kindly share any pointers to the Siw-M dataset.
