### ISSUE TITLE
Need suggestion for input 

### ISSUE THREAD

**Issue by GayatriPurandharT** [yaojieliu/ECCV20-STDN#7]
The input is both cropped face image and it's npy representation. Is there any specific program you used to generate crop and corresponding .npy file?
I did check your github link- https://github.com/yaojieliu/ICCVW2017-DenseFaceAlignment
I can't access the Basel Face Model (BFM) page that has been shared in the github page.
Also, does the 'DenseFaceAlignment' generate the corresponding npy for each input?
Thank you very much.

**Comment by yaojieliu** [comment]
You can also try https://github.com/1adrianb/face-alignment to obtain the landmarks. 
.npy file is basically a file to save numpy array. You can use numpy.save() and numpy.load() to access the .npy file.

**Comment by GayatriPurandharT** [comment]
Thank you for the clarification.
May I know the algorithm you used for cropping the faces from SiW-M video dataset?
